id: P008190
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4267
  title: ཇོ་ནང་པའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས་
  author: ''
  volumes:
    5841b74987fe478e99d20c6643b957d4:
      image_group_id: I1KG4993
      title: ''
      volume_number: 1
      total_pages: 230
      base_file: v001.txt
