id: I55849BF5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:24:25+00:00'
last_modified: '2022-06-09T05:07:37.648671+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4267
  title: ཇོ་ནང་པའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    74C2:
      image_group_id: I1KG4993
      title: ''
      total_pages: 230
      order: 1
      base_file: 74C2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
